using NetTopologySuite.Geometries;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Ntl.AuthSS.OrderManagement.Data.Entities
{
    public class Consumption
    {
        public Guid Id { get; set; }
        public string BatchNo { get; set; }
        public string AutoGeneratedBatchNo { get; set; }
        public DateTime ConsumptionDateTime { get; set; }
        public float GPSLatitude { get; set; }
        public float GPSLongitude { get; set; }
        [NotMappedAttribute]
        public Point GeoPoint { get; set; }
        public long TotalStamps { get; set; }
        public string SkuName { get; set; }
        public string BrandName { get; set; }
        //public ICollection<ConsumptionItem> ConsumptionItems { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Product Product { get; set; }
        public virtual StockKeepingUnit StockKeepingUnit { get; set; }
        public virtual OrgBrandProduct OrgBrandProduct { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public string ConsumedBy { get; set; }
        public string Consignee { get; set; }
        public string IPNumber { get; set; }
        public int CreatedUser { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ModifiedUser { get; set; }
        public DateTime ModifiedDate { get; set; }
        //public virtual TPSAFPayment TPSAFPayment { get; set; }
    }
}
